# Generated by Django 5.0.7 on 2024-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_username_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
