# Generated by Django 5.0.7 on 2024-10-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_remove_user_id_alter_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='userid',
        ),
    ]
