# Generated by Django 5.0.7 on 2024-10-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='body_type',
            new_name='bodyType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='selected_interests',
            new_name='selectedInterests',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='workout_frequency',
            new_name='workoutFrequency',
        ),
    ]
