# Generated by Django 5.0.7 on 2024-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_rename_body_type_user_bodytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bannerIcon',
            field=models.ImageField(blank=True, null=True, upload_to='banner_icons/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profileIcon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons/'),
        ),
    ]
