# Generated by Django 5.0.7 on 2024-10-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_alter_post_tags'),
        ('Backend', '0014_remove_user_bannericon_remove_user_bio_and_more'),
    ]

    operations = [
    ]
