# Generated by Django 5.0.7 on 2024-10-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_merge_20241027_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
