# Generated by Django 5.0.7 on 2024-11-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_alter_post_likes_alter_post_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
