# Generated by Django 5.0.7 on 2024-11-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.TextField(blank=True, null=True),
        ),
    ]
