# Generated by Django 5.0.7 on 2024-11-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_alter_post_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutType', models.CharField(max_length=100)),
                ('currentProgress', models.CharField(max_length=10)),
                ('progressGoal', models.CharField(max_length=10)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user')),
            ],
        ),
    ]
